name: Latest Blog Post Workflow
on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@TimelessRecall"
          max_post_count: 3
          
          date_format: "mmmm d, yyyy"
          
          template: "<table><tr><td width='250px'><a href='${url}' target='_blank'><img width='250px' src='${cover_image}' alt='${title}'></a></td><td valign='top'><a href='${url}' target='_blank'><h3>${title}</h3></a><i>${date}</i><p>${description}</p></td></tr></table><br>"
