name: Latest blog post workflow
on:
  schedule:

    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/timelessrecall"
          max_post_count: 5
          custom_format: '<table>$blog_post_list</table>'
          blog_post_list_format: |
            <tr>
              <td width="150px">
                <a href="$url" target="_blank">
                  <img src="$image" alt="$title" width="150">
                </a>
              </td>
              <td valign="top">
                <h3><a href="$url" target="_blank">$title</a></h3>
                <p>$description</p>
                <i>$date</i>
              </td>
            </tr>
